language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - NODE_VERSION="10.3.0"
  - NODE_VERSION="11"
  - NODE_VERSION="12"
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
  - pip install pytest
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
