language: python
python:
  - "3.5"
install:
  - nvm install 10.3.0
  - nvm use 10.3.0
  - npm install
  - pip install pytest
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
